"""Render the approved LYRA Balanced Lift runtime catalog.

The input is the reviewed, finite Piper/Cori source catalog generated by
``generate_lyra_voice_catalog.py``. Four phrases are taken directly from the
user-approved option-2 review master. The remaining fixed phrases use the
documented, deterministic matching profile below. FFmpeg and Rubber Band are
build-time tools only; the launcher ships only mono PCM16 WAV files.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import wave


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from src.audio.events import VOICE_LINE_TEXT, VoiceLine


DEFAULT_INPUT = REPOSITORY_ROOT / "scripts/voice_reference/lyra_cori_high_raw"
DEFAULT_REFERENCE = (
    REPOSITORY_ROOT
    / "scripts/voice_reference/lyra_balanced_lift_approved.mp3"
)
DEFAULT_OUTPUT = REPOSITORY_ROOT / "assets/audio/voice/lyra"
MANIFEST_NAME = "manifest.json"
PROFILE_ID = "lyra-balanced-lift-v1"
REFERENCE_SHA256 = (
    "9eccc3931db4689382d720602e691ff056155da8061bbfc1845795492d1702ef"
)
TARGET_MONO_LUFS = -18.35
LOUDNESS_TOLERANCE_LU = 0.03
MAX_GAIN_PASSES = 5

# The approved review master is four phrases separated by long digital-silence
# regions. End points are the starts of those regions, as detected at -42 dB
# for at least 120 ms. A short tail is added for comfortable runtime playback.
REFERENCE_SEGMENTS: dict[VoiceLine, tuple[float, float]] = {
    VoiceLine.PREVIEW: (0.0, 3.058750),
    VoiceLine.GAME_SERVER_LAUNCHING: (3.891729, 5.464708),
    VoiceLine.MARKET_SERVER_ONLINE: (6.353917, 8.156854),
    VoiceLine.LAUNCH_SEQUENCE_COMPLETE: (8.988833, 10.776000),
}
REFERENCE_PAD_SECONDS = 0.25

MATCHED_FILTER_TEMPLATE = ",".join(
    (
        # Padding prevents Rubber Band's analysis window from truncating
        # short operational phrases. It is removed again after stretching.
        "adelay=500",
        "apad=pad_dur=0.5",
        "rubberband=tempo=0.82:pitch=0.94166424:transients=smooth"
        ":detector=soft:phase=laminar:window=long:smoothing=on"
        ":formant=preserved:pitchq=consistency:channels=together",
        "atrim=start=0.6097560976:duration={duration_seconds}",
        "asetpts=PTS-STARTPTS",
        "highpass=f=70",
        "lowpass=f=10000",
        "equalizer=f=180:t=q:w=1:g=1.5",
        "equalizer=f=350:t=q:w=1.2:g=-1.0",
        "equalizer=f=2800:t=q:w=1.1:g=1.0",
        "equalizer=f=6500:t=q:w=1.2:g=-1.5",
        "acompressor=threshold=0.125:ratio=2.2:attack=15:release=150"
        ":makeup=1.5:knee=2.5:link=average:detection=rms:mix=1",
        "aresample=48000",
    )
)
LIMITER_FILTER = (
    "alimiter=level_in=1:level_out=1:limit=0.56234:attack=5:release=50"
    ":level=false:latency=true"
)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render the approved LYRA Balanced Lift WAV catalog."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--reference", type=Path, default=DEFAULT_REFERENCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--ffmpeg",
        default="ffmpeg",
        help="FFmpeg executable or absolute path (must include Rubber Band)",
    )
    return parser


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _safe_source_label(path: Path) -> str:
    """Return reproducible provenance without recording a private host path."""
    try:
        return path.resolve().relative_to(REPOSITORY_ROOT).as_posix()
    except ValueError:
        return f"<external>/{path.name}"


def _run(command: list[str], *, purpose: str) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(
        command,
        check=False,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if completed.returncode:
        detail = completed.stderr.strip() or completed.stdout.strip()
        raise SystemExit(f"FFmpeg failed while {purpose}:\n{detail}")
    return completed


def _resolve_ffmpeg(value: str) -> str:
    candidate = Path(value)
    if candidate.parent != Path(".") or candidate.is_absolute():
        if not candidate.is_file():
            raise SystemExit(f"Missing FFmpeg executable: {candidate}")
        return str(candidate.resolve())
    resolved = shutil.which(value)
    if resolved is None:
        raise SystemExit(f"FFmpeg executable not found on PATH: {value}")
    return resolved


def _ffmpeg_identity(ffmpeg: str) -> str:
    result = _run([ffmpeg, "-version"], purpose="reading its version")
    lines = result.stdout.splitlines()
    if not lines:
        raise SystemExit("FFmpeg returned no version information")
    configuration = "\n".join(lines)
    if "--enable-librubberband" not in configuration:
        raise SystemExit("FFmpeg was built without the required Rubber Band filter")
    return lines[0].strip()


def _load_source_manifest(root: Path) -> dict[str, object]:
    manifest_path = root / MANIFEST_NAME
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SystemExit(f"Invalid raw source manifest {manifest_path}: {exc}")
    if not isinstance(payload, dict):
        raise SystemExit(f"Invalid raw source manifest object: {manifest_path}")
    expected_identity = {
        "schema_version": 1,
        "catalog": "LYRA fixed operational voice lines",
        "voice": "Piper en_GB-cori-high",
        "voice_language": "en_GB",
    }
    mismatched_identity = [
        key for key, value in expected_identity.items()
        if payload.get(key) != value
    ]
    if mismatched_identity:
        raise SystemExit(
            "Raw source manifest has unexpected identity: "
            + ", ".join(mismatched_identity)
        )
    for hash_key in ("model_sha256", "config_sha256"):
        value = payload.get(hash_key)
        if (
            not isinstance(value, str)
            or re.fullmatch(r"[0-9a-f]{64}", value) is None
        ):
            raise SystemExit(
                f"Raw source manifest has invalid provenance: {hash_key}"
            )
    runtime = payload.get("generation_runtime")
    synthesis = payload.get("synthesis")
    licensing = payload.get("licensing")
    if not isinstance(runtime, str) or not runtime.startswith("piper-tts "):
        raise SystemExit(
            "Raw source manifest has invalid provenance: generation_runtime"
        )
    if not isinstance(synthesis, dict) or not isinstance(licensing, dict):
        raise SystemExit(
            "Raw source manifest has invalid provenance: synthesis/licensing"
        )
    clips = payload.get("clips")
    if not isinstance(clips, dict):
        raise SystemExit(f"Raw source manifest has no clip map: {manifest_path}")
    expected = {line.value for line in VoiceLine}
    if set(clips) != expected:
        raise SystemExit("Raw source manifest does not match the fixed LYRA catalog")
    return payload


def _validate_pcm16(path: Path) -> tuple[int, int, int, int]:
    try:
        with wave.open(str(path), "rb") as stream:
            result = (
                stream.getnchannels(),
                stream.getsampwidth(),
                stream.getframerate(),
                stream.getnframes(),
            )
    except (OSError, wave.Error) as exc:
        raise SystemExit(f"Invalid WAV {path}: {exc}")
    if result[:3] != (1, 2, 22_050) or result[3] <= 0:
        raise SystemExit(
            f"Invalid WAV format {path}: expected non-empty mono PCM16 at 22050 Hz"
        )
    return result


def _validate_raw_catalog(
    root: Path,
    manifest: dict[str, object],
) -> dict[VoiceLine, dict[str, object]]:
    raw_entries = manifest["clips"]
    assert isinstance(raw_entries, dict)
    validated: dict[VoiceLine, dict[str, object]] = {}
    for line in VoiceLine:
        path = root / line.filename
        entry = raw_entries.get(line.value)
        if not isinstance(entry, dict):
            raise SystemExit(f"Missing raw manifest entry: {line.value}")
        _validate_pcm16(path)
        actual_hash = _sha256(path)
        if (
            entry.get("text") != VOICE_LINE_TEXT[line]
            or entry.get("filename") != line.filename
            or entry.get("sha256") != actual_hash
        ):
            raise SystemExit(f"Raw source failed provenance validation: {path}")
        validated[line] = entry
    return validated


def _loudness_payload(stderr: str) -> dict[str, str]:
    matches = re.findall(
        r"\{\s*\"input_i\".*?\}",
        stderr,
        flags=re.DOTALL,
    )
    if not matches:
        raise SystemExit("FFmpeg loudness analysis returned no JSON payload")
    try:
        payload = json.loads(matches[-1])
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid FFmpeg loudness JSON: {exc}")
    if not isinstance(payload, dict):
        raise SystemExit("Invalid FFmpeg loudness result")
    return payload


def _measure_loudness(
    ffmpeg: str,
    path: Path,
    *,
    prefix_filter: str | None = None,
) -> tuple[float, float]:
    filters = "loudnorm=print_format=json"
    if prefix_filter:
        filters = f"{prefix_filter},{filters}"
    result = _run(
        [
            ffmpeg,
            "-hide_banner",
            "-nostats",
            "-nostdin",
            "-i",
            str(path),
            "-af",
            filters,
            "-f",
            "null",
            os.devnull,
        ],
        purpose=f"measuring {path.name}",
    )
    payload = _loudness_payload(result.stderr)
    try:
        integrated = float(payload["input_i"])
        true_peak = float(payload["input_tp"])
    except (KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"Invalid loudness values for {path}: {exc}")
    if not math.isfinite(integrated) or not math.isfinite(true_peak):
        raise SystemExit(f"Non-finite loudness values for {path}")
    return integrated, true_peak


def _matched_filter(source: Path) -> str:
    _, _, sample_rate, frames = _validate_pcm16(source)
    stretched_duration = (frames / sample_rate) / 0.82
    return MATCHED_FILTER_TEMPLATE.format(
        duration_seconds=f"{stretched_duration:.10f}"
    )


def _output_command(
    ffmpeg: str,
    source: Path,
    destination: Path,
    audio_filter: str,
) -> list[str]:
    return [
        ffmpeg,
        "-hide_banner",
        "-loglevel",
        "error",
        "-nostdin",
        "-y",
        "-i",
        str(source),
        "-map_metadata",
        "-1",
        "-fflags",
        "+bitexact",
        "-flags:a",
        "+bitexact",
        "-af",
        audio_filter,
        "-ar",
        "22050",
        "-ac",
        "1",
        "-c:a",
        "pcm_s16le",
        str(destination),
    ]


def _render_reference_extract(
    ffmpeg: str,
    reference: Path,
    destination: Path,
    segment: tuple[float, float],
) -> tuple[float, float, float | None]:
    start, end = segment
    audio_filter = ",".join(
        (
            f"atrim=start={start:.6f}:end={end:.6f}",
            "asetpts=PTS-STARTPTS",
            "pan=mono|c0=0.5*c0+0.5*c1",
            f"apad=pad_dur={REFERENCE_PAD_SECONDS}",
            "aresample=22050",
        )
    )
    _run(
        _output_command(ffmpeg, reference, destination, audio_filter),
        purpose=f"extracting approved phrase to {destination.name}",
    )
    integrated, true_peak = _measure_loudness(ffmpeg, destination)
    _validate_pcm16(destination)
    return integrated, true_peak, None


def _render_matched_profile(
    ffmpeg: str,
    source: Path,
    destination: Path,
) -> tuple[float, float, float]:
    matched_filter = _matched_filter(source)
    initial_lufs, _ = _measure_loudness(
        ffmpeg,
        source,
        prefix_filter=matched_filter,
    )
    gain_db = TARGET_MONO_LUFS - initial_lufs
    integrated = initial_lufs
    true_peak = 0.0
    for _ in range(MAX_GAIN_PASSES):
        audio_filter = ",".join(
            (
                matched_filter,
                f"volume={gain_db:.8f}dB",
                LIMITER_FILTER,
                "aresample=22050",
            )
        )
        _run(
            _output_command(ffmpeg, source, destination, audio_filter),
            purpose=f"processing {source.name}",
        )
        integrated, true_peak = _measure_loudness(ffmpeg, destination)
        correction = TARGET_MONO_LUFS - integrated
        if abs(correction) <= LOUDNESS_TOLERANCE_LU:
            break
        gain_db += correction
    else:
        raise SystemExit(
            f"Could not loudness-match {source.name}: {integrated:.2f} LUFS-I"
        )
    _validate_pcm16(destination)
    return integrated, true_peak, gain_db


def _clip_record(
    path: Path,
    line: VoiceLine,
    *,
    raw_entry: dict[str, object],
    method: str,
    integrated_lufs: float,
    true_peak_dbtp: float,
    gain_db: float | None,
) -> dict[str, object]:
    channels, sample_width, sample_rate, frames = _validate_pcm16(path)
    record: dict[str, object] = {
        "text": VOICE_LINE_TEXT[line],
        "filename": line.filename,
        "sha256": _sha256(path),
        "bytes": path.stat().st_size,
        "channels": channels,
        "sample_width_bytes": sample_width,
        "sample_rate_hz": sample_rate,
        "frames": frames,
        "raw_source_sha256": raw_entry["sha256"],
        "processing_method": method,
        "integrated_lufs": round(integrated_lufs, 2),
        "true_peak_dbtp": round(true_peak_dbtp, 2),
    }
    if gain_db is not None:
        record["matched_gain_db"] = round(gain_db, 8)
    return record


def _manifest(
    *,
    raw_manifest: dict[str, object],
    raw_manifest_path: Path,
    reference: Path,
    ffmpeg_identity: str,
    clips: dict[str, dict[str, object]],
) -> dict[str, object]:
    segments = {
        line.value: {
            "start_seconds": start,
            "end_seconds": end,
            "tail_pad_seconds": REFERENCE_PAD_SECONDS,
        }
        for line, (start, end) in REFERENCE_SEGMENTS.items()
    }
    return {
        "schema_version": 2,
        "catalog": "LYRA fixed operational voice lines",
        "voice": "LYRA Balanced Lift (Piper en_GB-cori-high source)",
        "voice_language": raw_manifest.get("voice_language", "en_GB"),
        "generation_runtime": raw_manifest.get("generation_runtime"),
        "model_source": raw_manifest.get("model_source"),
        "model_sha256": raw_manifest.get("model_sha256"),
        "config_sha256": raw_manifest.get("config_sha256"),
        "source_synthesis": raw_manifest.get("synthesis"),
        "licensing": raw_manifest.get("licensing"),
        "post_processing": {
            "profile_id": PROFILE_ID,
            "display_name": "Balanced Lift",
            "selection": "Option 2 selected from the lighter-voice review set",
            "processor": ffmpeg_identity,
            "raw_catalog": {
                "path": _safe_source_label(raw_manifest_path.parent),
                "manifest_sha256": _sha256(raw_manifest_path),
            },
            "approved_reference": {
                "path": _safe_source_label(reference),
                "sha256": REFERENCE_SHA256,
                "format": "48 kHz stereo MP3 at 192 kbps",
                "measured_stereo_lufs": -15.36,
                "measured_stereo_true_peak_dbtp": -4.32,
            },
            "reference_extracts": segments,
            "matched_profile_filter_template": MATCHED_FILTER_TEMPLATE,
            "matched_profile_target_mono_lufs": TARGET_MONO_LUFS,
            "matched_profile_loudness_tolerance_lu": LOUDNESS_TOLERANCE_LU,
            "limiter_filter": LIMITER_FILTER,
            "output": "mono PCM16 WAV at 22050 Hz",
        },
        "clips": clips,
    }


def main() -> None:
    args = _parser().parse_args()
    input_root = args.input.resolve()
    reference = args.reference.resolve()
    output = args.output.resolve()
    if input_root == output:
        raise SystemExit("Raw input and processed output directories must differ")
    if not input_root.is_dir():
        raise SystemExit(f"Missing raw LYRA source catalog: {input_root}")
    if not reference.is_file():
        raise SystemExit(f"Missing approved LYRA reference: {reference}")
    reference_hash = _sha256(reference)
    if reference_hash != REFERENCE_SHA256:
        raise SystemExit(
            "Approved LYRA reference hash mismatch: "
            f"expected {REFERENCE_SHA256}, got {reference_hash}"
        )

    ffmpeg = _resolve_ffmpeg(args.ffmpeg)
    ffmpeg_identity = _ffmpeg_identity(ffmpeg)
    raw_manifest_path = input_root / MANIFEST_NAME
    raw_manifest = _load_source_manifest(input_root)
    raw_entries = _validate_raw_catalog(input_root, raw_manifest)

    output.parent.mkdir(parents=True, exist_ok=True)
    expected_names = {line.filename for line in VoiceLine}
    if output.is_dir():
        extras = {path.name for path in output.glob("*.wav")} - expected_names
        if extras:
            raise SystemExit(
                "Refusing to process into a catalog with unexpected WAVs: "
                + ", ".join(sorted(extras))
            )

    with tempfile.TemporaryDirectory(
        prefix=".lyra-balanced-lift-",
        dir=output.parent,
    ) as temporary:
        stage = Path(temporary)
        clips: dict[str, dict[str, object]] = {}
        for index, line in enumerate(VoiceLine, start=1):
            destination = stage / line.filename
            raw_entry = raw_entries[line]
            if line in REFERENCE_SEGMENTS:
                integrated, true_peak, gain_db = _render_reference_extract(
                    ffmpeg,
                    reference,
                    destination,
                    REFERENCE_SEGMENTS[line],
                )
                method = "approved_reference_extract"
            else:
                integrated, true_peak, gain_db = _render_matched_profile(
                    ffmpeg,
                    input_root / line.filename,
                    destination,
                )
                method = "matched_profile"
            clips[line.value] = _clip_record(
                destination,
                line,
                raw_entry=raw_entry,
                method=method,
                integrated_lufs=integrated,
                true_peak_dbtp=true_peak,
                gain_db=gain_db,
            )
            print(
                f"[{index:02d}/{len(VoiceLine)}] {line.value}: {method}, "
                f"{integrated:.2f} LUFS-I, {true_peak:.2f} dBTP"
            )

        manifest = _manifest(
            raw_manifest=raw_manifest,
            raw_manifest_path=raw_manifest_path,
            reference=reference,
            ffmpeg_identity=ffmpeg_identity,
            clips=clips,
        )
        staged_manifest = stage / MANIFEST_NAME
        staged_manifest.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        output.mkdir(parents=True, exist_ok=True)
        for line in VoiceLine:
            os.replace(stage / line.filename, output / line.filename)
        # Publish the manifest last so runtime readiness never blesses a
        # partially replaced catalog.
        os.replace(staged_manifest, output / MANIFEST_NAME)

    print(f"Rendered {len(VoiceLine)} approved LYRA clips in {output}")
    print(f"Profile: {PROFILE_ID}")
    print(f"Manifest: {output / MANIFEST_NAME}")


if __name__ == "__main__":
    main()
